const empy = [
    {   
        id:1,
        name:"kumar",
        email:"kumar@gmail.com",
        age:30,
        phone:'575157584'
    },
    {   
        id:1,
        name:"kumar",
        email:"kumar@gmail.com",
        age:30,
        phone:'575157584'
    },
    {   
        id:1,
        name:"kumar",
        email:"kumar@gmail.com",
        age:30,
        phone:'575157584'
    },
    {   
        id:1,
        name:"kumar",
        email:"kumar@gmail.com",
        age:30,
        phone:'575157584'
    },
    {   
        id:1,
        name:"kumar",
        email:"kumar@gmail.com",
        age:30,
        phone:'575157584'
    },
    {   
        id:1,
        name:"kumar",
        email:"kumar@gmail.com",
        age:30,
        phone:'575157584'
    }

]